#!/usr/bin/env python
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain a
# copy of the License at:
#
#            http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.
#
# Written by Muthu Subramanian <sumuthu@novell.com>
#
import os
import sys

if len(sys.argv) < 3:
    print "Usage: "+sys.argv[0]+" <directory 1> <directory 2>"
    sys.exit(1)

ooxmldiff=os.path.dirname(sys.argv[0])+"/"+"ooxmldiff"

dir1=sys.argv[1]
dir2=sys.argv[2]
filenames=os.listdir(dir1)
for filename in filenames:
    file1=dir1+"/"+filename
    file2=dir2+"/"+filename
    if os.path.isfile(file1):
        print "Processing: "+file1
        os.system(ooxmldiff+" "+file1+" "+file2)
